//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace budgetplan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetItem
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public string Category { get; set; }
        public Nullable<int> Income { get; set; }
        public Nullable<int> BudgetedAmount { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
